### ISSUE TITLE
Error In all fragments...

### ISSUE THREAD

**Issue by nani3** [akshayejh/Lapit---Android-Firebase-Chat-App#1]
FirebaseRecyclerAdapter<Friends, FriendsViewHolder> friendsRecyclerViewAdapter = new FirebaseRecyclerAdapter<Friends, FriendsViewHolder>(

Hi Bro...
i got this error in all fragments....
how can i FIX this error's?
![kefjhdjn](https://user-images.githubusercontent.com/33892010/33645821-bd944e56-da72-11e7-86b0-0807d41ee00f.JPG)

**Comment by akshayejh** [comment]
Hi there, 

This project is not for direct Run and Use, you need to customize it according to your FIrebase Project and Tutorials provided to Run the App.
